name: Jest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        node-version: [14.x, 16.x, 18.x]
        jest-version: [26.x, 25.x, 24.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages and jest ${{ matrix.jest-version }}
        run: |
          npm ci
          npm install jest@${{ matrix.jest-version }} --save-dev
          npm run install-all-packages

      - name: Run tests
        run: npm run test
        env:
          CI: true
